version: '3'
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      # - PUID=1000
      # - PGID=1000
       - TZ=America/Chicago
    volumes:
      - ./config:/config
    ports:
      - 8080:80
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.heimdall.entrypoints=https"
      - "traefik.http.routers.heimdall.rule=Host(`heimdall.local.fatinc.org`)"
      - "traefik.http.routers.heimdall.tls=true"
      - "traefik.http.routers.heimdall.service=heimdall"
      - "traefik.http.services.heimdall.loadbalancer.server.port=8080"
      - "traefik.docker.network=proxy"
    restart: unless-stopped


networks:
  proxy:
    external: true  
