version: "3"

# More info at https://github.com/pi-hole/docker-pi-hole/ and https://docs.pi-hole.net/
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    # ports:
    # DNS Service Ports
    # - "53:53/tcp"
    # - "53:53/udp"
    # DHCP Service Ports
    # - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
    # PiHole WebUI
    # - "8053:80/tcp"
    network_mode: host
    environment:
      TZ: 'America/Chicago'
      DNSMASQ_LISTENING: local
      PIHOLE_DOMAIN: local.fatinc.org
      WEBTHEME: default-dark
      WEBPASSWORD_FILE: /var/run/secrets/webpassword
      WEB_PORT: 8053
      # DHCP Settings
      DHCP_ACTIVE: true
      DHCP_START: 192.168.1.10
      DHCP_END: 192.168.1.230
      DHCP_ROUTER: 192.168.1.1
    # Volumes store your data between container upgrades
    volumes:
      - './etc-pihole:/etc/pihole'
      - './etc-dnsmasq.d:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped
    # networks:
    # - proxy
    secrets:
      - webpassword
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.pihole.entrypoints=https"
    #   - "traefik.http.routers.pihole.rule=Host(`pihole.local.fatinc.org`)"
    #   - "traefik.http.routers.pihole.tls=true"
    #   - "traefik.http.routers.pihole.service=pihole"
    #   - "traefik.http.services.pihole.loadbalancer.server.port=80"
    #   - "traefik.docker.network=proxy"

# networks:
  # proxy:
    # external: true  

secrets:
  webpassword:
    file: ./pihole-password.secret
