version: '3'
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.home-assistant.entrypoints=https"
      - "traefik.http.routers.home-assistant.rule=Host(`home-assistant.local.fatinc.org`)"
      - "traefik.http.routers.home-assistant.tls=true"
      - "traefik.http.routers.home-assistant.service=home-assistant"
      - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true  