version: '3'
services:
  zwave-js:
    container_name: zwave-js-ui
    image: zwavejs/zwave-js-ui:latest
    restart: always
    tty: true
    stop_signal: SIGINT
    environment:
      - ZWAVEJS_EXTERNAL_CONFIG=/usr/src/app/store/.config-db
      # Uncomment if you want logs time and dates to match your timezone instead of UTC
      # Available at https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
      - TZ=America/Chicago
    networks:
      - proxy
    devices:
      # Do not use /dev/ttyUSBX serial devices, as those mappings can change over time.
      # Instead, use the /dev/serial/by-id/X serial device for your Z-Wave stick.
      - '/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_8696a66f1055ed11a13693131d62bc44-if00-port0:/dev/zwave'
    volumes:
      - ./zwave-config:/usr/src/app/store
    ports:
      - '8091:8091' # port for web interface
      - '3000:3000' # port for Z-Wave JS websocket server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.zwave-js.entrypoints=https"
      - "traefik.http.routers.zwave-js.rule=Host(`zwave-js.local.fatinc.org`)"
      - "traefik.http.routers.zwave-js.tls=true"
      - "traefik.http.routers.zwave-js.service=zwave-js"
      - "traefik.http.services.zwave-js.loadbalancer.server.port=8091"
      - "traefik.docker.network=proxy"

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ./config:/config
      - /etc/localtime:/etc/localtime:ro
      - /run/dbus:/run/dbus:ro
    restart: unless-stopped
    privileged: true
    network_mode: host

    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.home-assistant.entrypoints=https"
    #   - "traefik.http.routers.home-assistant.rule=Host(`home-assistant.local.fatinc.org`)"
    #   - "traefik.http.routers.home-assistant.tls=true"
    #   - "traefik.http.routers.home-assistant.service=home-assistant"
    #   - "traefik.http.services.home-assistant.loadbalancer.server.port=8123"
    #   - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true  
